apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          ports:
            - containerPort: PORT_CONTAINER

          env:
            - name: API_GLOBAL_PREFIX
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: API_GLOBAL_PREFIX
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: EMAIL_USER
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: EMAIL_PASSWORD
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: EMAIL_HOST
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: EMAIL_PORT
            - name: IS_SWAGGER_ENABLED
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: IS_SWAGGER_ENABLED
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: POSTGRES_URL
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: ACCESS_TOKEN_SECRET
            - name: ACCESS_TOKEN_LIFETIME
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: ACCESS_TOKEN_LIFETIME
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: REFRESH_TOKEN_SECRET
            - name: REFRESH_TOKEN_LIFETIME
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: REFRESH_TOKEN_LIFETIME
            - name: LIMIT_REQUEST_IN_TTL
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: LIMIT_REQUEST_IN_TTL
            - name: TTL_IN_SECONDS
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: TTL_IN_SECONDS
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: main-gateway-production-config-secret
                  key: NODE_ENV
