apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: GLOBAL_PREFIX
               valueFrom:
                 secretKeyRef:
                   name: main-gateway-production-config-secret
                   key: GLOBAL_PREFIX
             - name: EMAIL_USER
               valueFrom:
                 secretKeyRef:
                   name: main-gateway-production-config-secret
                   key: EMAIL_USER
             - name: EMAIL_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: main-gateway-production-config-secret
                   key: EMAIL_PASSWORD
             - name: EMAIL_HOST
               valueFrom:
                 secretKeyRef:
                   name: main-gateway-production-config-secret
                   key: EMAIL_HOST
             - name: EMAIL_PORT
               valueFrom:
                 secretKeyRef:
                   name: main-gateway-production-config-secret
                   key: EMAIL_PORT
             - name: IS_SWAGGER_ENABLED
               valueFrom:
                 secretKeyRef:
                   name: main-gateway-production-config-secret
                   key: IS_SWAGGER_ENABLED
             - name: POSTGRES_HOST
               valueFrom:
                 secretKeyRef:
                   name: main-gateway-production-config-secret
                   key: POSTGRES_HOST
             - name: POSTGRES_DB
               valueFrom:
                 secretKeyRef:
                   name: main-gateway-production-config-secret
                   key: POSTGRES_DB
             - name: POSTGRES_USER
               valueFrom:
                 secretKeyRef:
                   name: main-gateway-production-config-secret
                   key: POSTGRES_USER
             - name: POSTGRES_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: main-gateway-production-config-secret
                   key: POSTGRES_PASSWORD
             - name: POSTGRES_URI
               valueFrom:
                 secretKeyRef:
                   name: main-gateway-production-config-secret
                   key: POSTGRES_URI
             - name: NODE_ENV
               valueFrom:
                 secretKeyRef:
                   name: main-gateway-production-config-secret
                   key: NODE_ENV
