services:
  postgres:
    image: postgres:17
    container_name: gateway-postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=JustMyShots-Dev
    ports:
      - '5400:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: